<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \App\Models\Car::insert([
            [
                'name' => 'Toyota Camry',
                'user_id' => 1,
                'brand_id' => 1,
                'type_id' => 1,
                'city_id' => 1,
                'desc' => 'A comfortable midsize sedan with great fuel efficiency.',
                'total_seat' => 5,
                'gear_system' => 'Auto',
                'fuel_type' => 'Petrol',
                'engine_hp' => 203,
                'color' => 'White',
                'car_number' => 'ABC123',
                'rental_price' => 55.00,
            ],
            [
                'name' => 'Honda CR-V',
                'user_id' => 1,
                'brand_id' => 2,
                'type_id' => 2,
                'city_id' => 2,
                'desc' => 'A spacious SUV with advanced safety features.',
                'total_seat' => 5,
                'gear_system' => 'Auto',
                'fuel_type' => 'Petrol',
                'engine_hp' => 190,
                'color' => 'Black',
                'car_number' => 'XYZ789',
                'rental_price' => 65.00,
            ],
            [
                'name' => 'Ford Mustang',
                'user_id' => 1,
                'brand_id' => 3,
                'type_id' => 4,
                'city_id' => 3,
                'desc' => 'A classic American muscle car with powerful performance.',
                'total_seat' => 4,
                'gear_system' => 'Manual',
                'fuel_type' => 'Petrol',
                'engine_hp' => 450,
                'color' => 'Red',
                'car_number' => 'MUS456',
                'rental_price' => 120.00,
            ],
            [
                'name' => 'Chevrolet Bolt EV',
                'user_id' => 1,
                'brand_id' => 4,
                'type_id' => 10,
                'city_id' => 4,
                'desc' => 'An all-electric hatchback with impressive range and technology.',
                'total_seat' => 5,
                'gear_system' => 'Auto',
                'fuel_type' => 'Electric',
                'engine_hp' => 200,
                'color' => 'Blue',
                'car_number' => 'ELE789',
                'rental_price' => 80.00,
            ],
            [
                'name' => 'Nissan Altima',
                'user_id' => 1,
                'brand_id' => 5,
                'type_id' => 1,
                'city_id' => 5,
                'desc' => 'A stylish sedan with a comfortable interior and smooth ride.',
                'total_seat' => 5,
                'gear_system' => 'Auto',
                'fuel_type' => 'Petrol',
                'engine_hp' => 188,
                'color' => 'Silver',
                'car_number' => 'ALT321',
                'rental_price' => 50.00,
            ],
            [
                'name' => 'BMW X5',
                'user_id' => 1,
                'brand_id' => 6,
                'type_id' => 2,
                'city_id' => 1,
                'desc' => 'A luxury SUV with powerful performance and advanced features.',
                'total_seat' => 5,
                'gear_system' => 'Auto',
                'fuel_type' => 'Diesel',
                'engine_hp' => 335,
                'color' => 'Gray',
                'car_number' => 'BMWX5',
                'rental_price' => 150.00,
            ],
            [
                'name' => 'Mercedes-Benz C-Class',
                'user_id' => 1,
                'brand_id' => 7,
                'type_id' => 1,
                'city_id' => 2,
                'desc' => 'A premium sedan with elegant design and cutting-edge technology.',
                'total_seat' => 5,
                'gear_system' => 'Auto',
                'fuel_type' => 'Petrol',
                'engine_hp' => 255,
                'color' => 'Black',
                'car_number' => 'MBZC300',
                'rental_price' => 140.00,
            ],
            [
                'name' => 'Volkswagen Golf',
                'user_id' => 1,
                'brand_id' => 8,
                'type_id' => 3,
                'city_id' => 3,
                'desc' => 'A compact hatchback with sporty handling and efficient performance.',
                'total_seat' => 5,
                'gear_system' => 'Manual',
                'fuel_type' => 'Diesel',
                'engine_hp' => 147,
                'color' => 'Blue',
                'car_number' => 'VWGOLF',
                'rental_price' => 45.00,
            ],
            [
                'name' => 'Audi Q5',
                'user_id' => 1,
                'brand_id' => 9,
                'type_id' => 2,
                'city_id' => 4,
                'desc' => 'A luxury crossover SUV with a refined interior and advanced technology.',
                'total_seat' => 5,
                'gear_system' => 'Auto',
                'fuel_type' => 'Petrol',
                'engine_hp' => 261,
                'color' => 'White',
                'car_number' => 'AUDIQ5',
                'rental_price' => 65.00,
            ],
            [
                'name' => 'Hyundai Sonata',
                'user_id' => 1,
                'brand_id' => 10,
                'type_id' => 1,
                'city_id' => 5,
                'desc' => 'A midsize sedan with a sleek design and advanced safety features.',
                'total_seat' => 5,
                'gear_system' => 'Auto',
                'fuel_type' => 'Hybrid',
                'engine_hp' => 192,
                'color' => 'Red',
                'car_number' => 'HYUSON',
                'rental_price' => 60.00,
            ],
        ]);
    }
};
